name: Conventional Commits

on:
  pull_request_target:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Report Conventional Commits
        uses: greenbone/actions/conventional-commits@v2
